/* gtk-sync-sample.c generated by valac 0.20.1, the Vala compiler
 * generated from gtk-sync-sample.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_SYNC_SAMPLE (sync_sample_get_type ())
#define SYNC_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SYNC_SAMPLE, SyncSample))
#define SYNC_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SYNC_SAMPLE, SyncSampleClass))
#define IS_SYNC_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SYNC_SAMPLE))
#define IS_SYNC_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SYNC_SAMPLE))
#define SYNC_SAMPLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SYNC_SAMPLE, SyncSampleClass))

typedef struct _SyncSample SyncSample;
typedef struct _SyncSampleClass SyncSampleClass;
typedef struct _SyncSamplePrivate SyncSamplePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _SyncSample {
	GtkWindow parent_instance;
	SyncSamplePrivate * priv;
	GtkButton* ok;
	GtkButton* cancel;
};

struct _SyncSampleClass {
	GtkWindowClass parent_class;
};

struct _SyncSamplePrivate {
	GtkSpinButton* spin_box;
	GtkScale* slider;
};


static gpointer sync_sample_parent_class = NULL;

GType sync_sample_get_type (void) G_GNUC_CONST;
#define SYNC_SAMPLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SYNC_SAMPLE, SyncSamplePrivate))
enum  {
	SYNC_SAMPLE_DUMMY_PROPERTY
};
SyncSample* sync_sample_new (void);
SyncSample* sync_sample_construct (GType object_type);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void __lambda2_ (SyncSample* self);
static void ___lambda2__gtk_adjustment_value_changed (GtkAdjustment* _sender, gpointer self);
static void __lambda3_ (SyncSample* self);
static void ___lambda3__gtk_adjustment_value_changed (GtkAdjustment* _sender, gpointer self);
gint sync_sample_main (gchar** args, int args_length1);
static void sync_sample_finalize (GObject* obj);


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


static void __lambda2_ (SyncSample* self) {
	GtkScale* _tmp0_;
	GtkAdjustment* _tmp1_;
	GtkAdjustment* _tmp2_;
	GtkSpinButton* _tmp3_;
	GtkAdjustment* _tmp4_;
	GtkAdjustment* _tmp5_;
	gdouble _tmp6_;
	gdouble _tmp7_;
	_tmp0_ = self->priv->slider;
	_tmp1_ = gtk_range_get_adjustment ((GtkRange*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = self->priv->spin_box;
	_tmp4_ = gtk_spin_button_get_adjustment (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = gtk_adjustment_get_value (_tmp5_);
	_tmp7_ = _tmp6_;
	gtk_adjustment_set_value (_tmp2_, _tmp7_);
}


static void ___lambda2__gtk_adjustment_value_changed (GtkAdjustment* _sender, gpointer self) {
	__lambda2_ (self);
}


static void __lambda3_ (SyncSample* self) {
	GtkSpinButton* _tmp0_;
	GtkAdjustment* _tmp1_;
	GtkAdjustment* _tmp2_;
	GtkScale* _tmp3_;
	GtkAdjustment* _tmp4_;
	GtkAdjustment* _tmp5_;
	gdouble _tmp6_;
	gdouble _tmp7_;
	_tmp0_ = self->priv->spin_box;
	_tmp1_ = gtk_spin_button_get_adjustment (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = self->priv->slider;
	_tmp4_ = gtk_range_get_adjustment ((GtkRange*) _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = gtk_adjustment_get_value (_tmp5_);
	_tmp7_ = _tmp6_;
	gtk_adjustment_set_value (_tmp2_, _tmp7_);
}


static void ___lambda3__gtk_adjustment_value_changed (GtkAdjustment* _sender, gpointer self) {
	__lambda3_ (self);
}


SyncSample* sync_sample_construct (GType object_type) {
	SyncSample * self = NULL;
	GtkSpinButton* _tmp0_;
	GtkScale* _tmp1_;
	GtkSpinButton* _tmp2_;
	GtkAdjustment* _tmp3_;
	GtkAdjustment* _tmp4_;
	GtkScale* _tmp5_;
	GtkAdjustment* _tmp6_;
	GtkAdjustment* _tmp7_;
	GtkSpinButton* _tmp8_;
	GtkAdjustment* _tmp9_;
	GtkAdjustment* _tmp10_;
	GtkBox* _tmp11_;
	GtkBox* hbox;
	GtkSpinButton* _tmp12_;
	GtkScale* _tmp13_;
	self = (SyncSample*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "Enter your age");
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_window_set_default_size ((GtkWindow*) self, 300, 20);
	_tmp0_ = (GtkSpinButton*) gtk_spin_button_new_with_range ((gdouble) 0, (gdouble) 130, (gdouble) 1);
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->spin_box);
	self->priv->spin_box = _tmp0_;
	_tmp1_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_HORIZONTAL, (gdouble) 0, (gdouble) 130, (gdouble) 1);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->slider);
	self->priv->slider = _tmp1_;
	_tmp2_ = self->priv->spin_box;
	_tmp3_ = gtk_spin_button_get_adjustment (_tmp2_);
	_tmp4_ = _tmp3_;
	g_signal_connect_object (_tmp4_, "value-changed", (GCallback) ___lambda2__gtk_adjustment_value_changed, self, 0);
	_tmp5_ = self->priv->slider;
	_tmp6_ = gtk_range_get_adjustment ((GtkRange*) _tmp5_);
	_tmp7_ = _tmp6_;
	g_signal_connect_object (_tmp7_, "value-changed", (GCallback) ___lambda3__gtk_adjustment_value_changed, self, 0);
	_tmp8_ = self->priv->spin_box;
	_tmp9_ = gtk_spin_button_get_adjustment (_tmp8_);
	_tmp10_ = _tmp9_;
	gtk_adjustment_set_value (_tmp10_, (gdouble) 35);
	_tmp11_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 5);
	g_object_ref_sink (_tmp11_);
	hbox = _tmp11_;
	gtk_box_set_homogeneous (hbox, TRUE);
	_tmp12_ = self->priv->spin_box;
	gtk_container_add ((GtkContainer*) hbox, (GtkWidget*) _tmp12_);
	_tmp13_ = self->priv->slider;
	gtk_container_add ((GtkContainer*) hbox, (GtkWidget*) _tmp13_);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) hbox);
	_g_object_unref0 (hbox);
	return self;
}


SyncSample* sync_sample_new (void) {
	return sync_sample_construct (TYPE_SYNC_SAMPLE);
}


gint sync_sample_main (gchar** args, int args_length1) {
	gint result = 0;
	SyncSample* _tmp0_;
	SyncSample* window;
	gtk_init (&args_length1, &args);
	_tmp0_ = sync_sample_new ();
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) window);
	gtk_main ();
	result = 0;
	_g_object_unref0 (window);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return sync_sample_main (argv, argc);
}


static void sync_sample_class_init (SyncSampleClass * klass) {
	sync_sample_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SyncSamplePrivate));
	G_OBJECT_CLASS (klass)->finalize = sync_sample_finalize;
}


static void sync_sample_instance_init (SyncSample * self) {
	self->priv = SYNC_SAMPLE_GET_PRIVATE (self);
}


static void sync_sample_finalize (GObject* obj) {
	SyncSample * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SYNC_SAMPLE, SyncSample);
	_g_object_unref0 (self->ok);
	_g_object_unref0 (self->cancel);
	_g_object_unref0 (self->priv->spin_box);
	_g_object_unref0 (self->priv->slider);
	G_OBJECT_CLASS (sync_sample_parent_class)->finalize (obj);
}


GType sync_sample_get_type (void) {
	static volatile gsize sync_sample_type_id__volatile = 0;
	if (g_once_init_enter (&sync_sample_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SyncSampleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sync_sample_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SyncSample), 0, (GInstanceInitFunc) sync_sample_instance_init, NULL };
		GType sync_sample_type_id;
		sync_sample_type_id = g_type_register_static (GTK_TYPE_WINDOW, "SyncSample", &g_define_type_info, 0);
		g_once_init_leave (&sync_sample_type_id__volatile, sync_sample_type_id);
	}
	return sync_sample_type_id__volatile;
}



