/* gtk-sync-sample.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __GTK_SYNC_SAMPLE_H__
#define __GTK_SYNC_SAMPLE_H__

#include <glib.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define TYPE_SYNC_SAMPLE (sync_sample_get_type ())
#define SYNC_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SYNC_SAMPLE, SyncSample))
#define SYNC_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SYNC_SAMPLE, SyncSampleClass))
#define IS_SYNC_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SYNC_SAMPLE))
#define IS_SYNC_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SYNC_SAMPLE))
#define SYNC_SAMPLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SYNC_SAMPLE, SyncSampleClass))

typedef struct _SyncSample SyncSample;
typedef struct _SyncSampleClass SyncSampleClass;
typedef struct _SyncSamplePrivate SyncSamplePrivate;

struct _SyncSample {
	GtkWindow parent_instance;
	SyncSamplePrivate * priv;
	GtkButton* ok;
	GtkButton* cancel;
};

struct _SyncSampleClass {
	GtkWindowClass parent_class;
};


GType sync_sample_get_type (void) G_GNUC_CONST;
SyncSample* sync_sample_new (void);
SyncSample* sync_sample_construct (GType object_type);
gint sync_sample_main (gchar** args, int args_length1);


G_END_DECLS

#endif
